theme: jekyll-theme-midnight
title: Online Experiments for Language Scientists
description: Academic year 2020-2021
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - oels_reading_wk2.md
